### ISSUE TITLE
How to hide/disable the type drop down list after a field

### ISSUE THREAD

**Issue by ricklxm** [rodikh/angular-json-editor#14]
![image](https://cloud.githubusercontent.com/assets/4877955/7975671/4ace6eb6-0aa3-11e5-8018-8ca1877b36f5.png)

**Comment by rodikh** [comment]
Hey Rick,
The dropdown only shows up if you do not define a specific type for the property.

You need to define a type in the schema object.

    "customerMobile": {
      "type": "string"
    }

**Comment by ricklxm** [comment]
I do have defined the type for "customerMobile". See the whole schema below, there are some chinese in the title field, hope that doesn't matter.
{
  "type": "object",
  "title": "查询",
  "format": "grid",
  "properties": {
    "query": {
      "type": "object",
      "title": "查询条件",
      "properties": {
        "agentMobile": {
          "type": "string",
          "title": "业务员手机号码",
          "required": true
        },
        "customerMobile": {
          "type": "string",
          "title": "客户手机号码",
          "required": true
        }
      }
    },
    "result": {
      "type": "object",
      "title": "查询结果",
      "properties": {
        "refundInfo": {
          "type": "object",
          "title": "处理进度",
          "properties": {
            "agentName": {
              "title": "申请人",
              "type": "string"
            },
            "status": {
              "title": "状态",
              "type": "string"
            },
            "reason": {
              "title": "原因",
              "type": "string"
            },
            "refundEvents": {
              "type": "array",
              "title": "历史流程",
              "items": [
                {
                  "$ref": "event.json"
                }
              ]
            },
            "info": {
              "$ref": "customerInfo.json"
            }
          }
        }
      }
    }
  }
}

**Comment by rodikh** [comment]
I can't seem to reproduce your case.
I am using your schema, minus the $ref fields, and i'm getting the customerMobile field without a dropdown.

I've also tried to insert your schema on http://jeremydorn.com/json-editor/ and I still get the correct result.

Your case could happen if you define a value in startVal, that you didn't define in the schema. (in this case it will create a new property without a set type but with a dropdown).
maybe you have a typo in startVal? in query, or customerMobile?
Can you share more of your code?

**Comment by ricklxm** [comment]
Thanks very much for trying help. My code is as below:
app
    .controller('refundQueryNgJsonEditorCtrl', function($scope, $http, $timeout, modal) {
        $scope.init = function() {
            $scope.process = {
                title: '退款查询'
            };

            $scope.schema = $http.get('./json/schemaAll.json') || {};

            $scope.startVal = $http.get('./json/data.json') || {};
        };
		
		
// data.json
{
  "agentMobile": "1111111111",
  "customerMobile": "2222222222"
}

Perhaps the root casue is I get the $scope.startVal before get the $scope.schema? 
So what the right way to read the schema and startVal both from server?

Another quick question: 
Is it possible to use the same controller for both the editor and the submit button? Because I'd like to use some object defined inside of editor's controller in the ng-click handler for the button. 

Thanks again for your help.

**Comment by rodikh** [comment]
please switch to master branch, and let me know if the issue is solved for you.
I'll push it to a new tag in a few days.

As for the buttons controller, I have a big restructure planned for that area, so I advise adding regular buttons outside my directive until I get a new version out.
