### ISSUE TITLE
async editor doesn't take into account "format" schema property

### ISSUE THREAD

**Issue by nirfrank** [rodikh/angular-json-editor#17]
I'm attempting to use Ace Editor in my editor.

When hard-coding my starting value, the editor respects the "format" schema property and properly loads Ace Editor in the respective fields.

When loading my starting value via a promise, the data will load, but Ace Editor will not toggle in the fields under which its supposed to be enabled.

If I should add any more technical details here which I haven't, let me know and I will (first time opening an issue in GitHub).

**Comment by rodikh** [comment]
Hey Nir,
I'll look into the issue when I'm off work. 

In the meanwhile, can you post some of the relevant parts of your schema file and starting value?
Just enough for me to recreate the issue. 

Toda raba.

**Comment by nirfrank** [comment]
Ahalan Rodikh :)

I looked into it. I'm not sure exactly what in my set up caused this bug to happen, but I rewrote the factory responsible - still returned a promise, this time via $q instead of $http - and it works as expected. Weird!

I'll try to re-create the issue on my own personal time and get in touch. I'll close the issue till then, if that's alright. Thanks for the hard work!
