### ISSUE TITLE
json-editor startval doesn't get updated in case of async load

### ISSUE THREAD

**Issue by RumenTech** [rodikh/angular-json-editor#18]
Hi,

My HTML is as follows.
`<json-editor schema="model.schema" startval="model.jsonValue" on-change="valueChanged($editorValue)"></json-editor>`

I load model by async http call and this directive gets compiled before model gets real value.
Is there any way to provide 2-way binding with json variable itself rather than linking on-change function?

Thank you.

**Comment by rodikh** [comment]
I am working on a long term solution to the problem of an async startVal.

For now, there are a few different solutions available at #12
