### ISSUE TITLE
SCEditor - set readonly true.

### ISSUE THREAD

**Issue by elijahvsjesus** [rodikh/angular-json-editor#19]
Hello,

First of all, thanks for the awesome job with angular-json-editor.

When my angular view is loaded, I need to "disable" angular-json-editor through my controller.

For that, no problem using the "$scope.editor.disable();" function.

But, when a SCeditor is loaded within my JSON Schema, it does not get disabled. Reading the SCeditor, I've found in their API they have the "readonly" function that can be set to true on the fly. (ref.: http://www.sceditor.com/api/sceditor/readonly/)

The question is: whats the instance, inside $scope.editor to find the sceditor and fire this function?

**Comment by rodikh** [comment]
Hey,

You can configure plugins by using the configure method on the JSONEditorProvider object in your module().config phase.
here is an example using the demo configuration:
```javascript
angular.module('demoApp', ['angular-json-editor']).config(function (JSONEditorProvider) {
    // these are set by default, but we set this for demonstration purposes
    JSONEditorProvider.configure({
        plugins: {
            sceditor: {
                readOnly: true
            }
        }
    });
})
```

If you want to change a specific editor, you can find the sceditor instance by using this path:
```javascript
$scope.editor.getEditor("root.fieldName").sceditor_instance.readOnly(true);
```

**Comment by elijahvsjesus** [comment]
Thank you very much, worked like a charm. :D

The second suggestion was what I was looking for.
