### ISSUE TITLE
Alternative project with ng-model and schema change binding

### ISSUE THREAD

**Issue by Maks3w** [rodikh/angular-json-editor#20]
I've found this other project with additional AngularJS features wrapping JSON Editor too.

https://github.com/mohsen1/angular-json-schema-form

May both developers could join efforts.

**Comment by Maks3w** [comment]
It seems that your attitude towards the community is clear

**Comment by rodikh** [comment]
Hey @Maks3w,

**Comment by rodikh** [comment]
Hey @Maks3w,
I am not ignoring your request :) no need to get offended.
I'm just cleaning up the issues to maintain only technical issues. I'll see if I can cooperate with mohsen1 after i get some of the technical stuff out of the way.

Thanks for helping

**Comment by shikshik** [comment]
Hi there,
Before we chose our solution, we worked with "angular-json-schema-form" and it doesn't fully support JSON schema as your project does (Thumbs up).

But... their approach is much easier to understand and to work with (and still we chose your work since the standard matters).

**Comment by rodikh** [comment]
Hey @shikshik,
Thanks for supporting my project.
My project doesn't actually do anything other than wrap [jdorn/json-editor] (https://github.com/jdorn/json-editor) in an angular directive.

So he is the one who actually deserves the thumbs up.

**Comment by shikshik** [comment]
:+1:
