### ISSUE TITLE
New version bug

### ISSUE THREAD

**Issue by shikshik** [rodikh/angular-json-editor#21]
Just updated to new version (We needed that auto-update feature - almost forked myself to do it), seems like the output is broken, It does render the UI but it looks broken (useless select boxes appears). before your update, we used the same schema and got perfectly rendered. I double checked my data and schema, nothing has changed except angular-json-editor version.

Can you please re-check your latest version?
I will keep investigating and update if I've found anything.

**Comment by rodikh** [comment]
Can you give me some more info?
maybe paste some outputs?

The main change on the recent update was to the way I read the promises of startVal and schema scope variables. paste an example of what your startVal and schema variables contain.

**Comment by shikshik** [comment]
We don't use startVal, it is part of the default schema we pull (schema is auto-generated in server side).
So I thought it might be the case, so I checked how you handle the startVal in the directive, it is optional as far as I can see (and worked like that with old version of angular-json-editor).

Attached screenshot shows how it got broken. it does show the correct inputs but it adds some wired select boxes for each input field. 

![screenshot from 2015-11-01 17 19 02](https://cloud.githubusercontent.com/assets/6535924/10869597/b2a9d69e-80bc-11e5-957a-405f7163ca36.png)

**Comment by shikshik** [comment]
After drilling the directive... I've found that your are waiting for promise from both schema and startVal. But in that case, nothing suppose to happen. instead I see the rendered form (as in my screenshot).

Added a console after "q.all([schemaPromise, startValPromise]" and it does not get there... so how and why does it renders?

**Comment by shikshik** [comment]
Without startVal, this is what the startValPromise looks like inside the listener when printing to the console:

$$state: Object
pending: undefined
processScheduled: false
status: 1
value: Object

You can see the it's value is an object, but an empty object. So the logics might be wrong, maybe you should check if there is data in startVal (but make sure it is optional!).

Anyway, i'm still not sure what is causing me that issue with weird rendering. I can still pull the correct data out of the rendered editor (with getValue method).

Any idea?

**Comment by rodikh** [comment]
Promise.all should work in both cases (when receiving a promise and when receiving a value).

I'll take a look at the different cases and see what's wrong.

**Comment by shikshik** [comment]
Thanks!
I'm constantly testing, and it seems like the only change that affects my rendering is the fact that I don't pass the startVal at all. I might be wrong.

**Comment by rodikh** [comment]
Can you share a sample schema?

**Comment by rodikh** [comment]
These select boxes are property type selection boxes. The editor shows them when it doesn't know which type (string/integer/object) a certain property is. this usually happens when you set a default value or a startval for a property that doesn't show up in a schema.

This leads me to believe that your schema doesn't register correctly.

**Comment by shikshik** [comment]
Thanks, I will check it again, but still, it hasn't been changed, only updated the angular editor directive.

**Comment by shikshik** [comment]
Here is a link to my schema:
https://gist.github.com/shikshik/e8509b63f7b5659ba727

We checked again and it seems fine. I would appreciate your assistance.

**Comment by shikshik** [comment]
After too many hours of testing... I've tried separating the startval from the schema, and found that it is the statval promise fault.
What I did is manually define the startval object in the scope, schema object is an ajax promise ($http).
Now it works (without the startval values, but i guess I can fix it). when assigning the startval data dynamically after schema promise is resolved, things go wild with the rendering.

Please let me know if it's my approach to promise that messing it up or is it something to do with better supporting startval promises inside the directive.

**Comment by rodikh** [comment]
רגע... אתה ישראלי?

**Comment by shikshik** [comment]
Yep :smile:

**Comment by shikshik** [comment]
Just tried passing startVal as promise like the schema data, found that it never passes as an object and those lines never true:

if (angular.isObject(scope.startval)) {
       // Support both $http (i.e. $q) and $resource promises, and also normal object.
       startValPromise = $q.when(scope.startval);
 }
