### ISSUE TITLE
Schema Issue with Array

### ISSUE THREAD

**Issue by elijahvsjesus** [rodikh/angular-json-editor#22]
Hello,

I have this schema:
http://pastebin.com/W1Yf3f7m

When I try to parse it at original JSON Editor sandbox, no problem at all. I can see the original properties plus the Images and Images2 sub-levels with array and add button:
Ref.: [Example at JSON Editor Sandbox](http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAUCHBzCA7AhgZxABpwBPAB3iQHsAjAK1gGMwiQAnWARwFcIOATRGDbdYxHP35QIVXNGRsqFNpFgEEAMxzQ8YkGUXLV60LgC2lUJBiUQAOSoWAVKzDlbeYdnSsNVNmY4LEiebN6sHDx8sIIIwqLEZtgAMrBY6GAAFogAjIk4AB6p6Vm5AJw5AL7E/GqMYWSQsohWUHCIIAAidWEA5wDHVK7uHaHhxH4BQR2ZYGbQEVy8AkIieklYxRnZCAAM+UVp24gArDkATMRKTVgmIADuJHgQjz5xa5XVIHiZ/mC1eHqEEaMiwLXAbVs3UBfUGAAIAMLcFQ4YYUUZedK+fyBYLfTE+YiRZYxVYJEAbLalPYHKk7HIVL4QQLoNTncExVkdZk4Vl4dnEaztJAASRZbLRthwbDYOBI2KmeLAOBo7WI3CwEB4sBFYFgZnU8T0UH1dyFtjFvIlgpG1HoTBYRKW0ViRvEkmksm0CiUsBUEDUiC0Oj0Bl9/sDCFAnMsEJsHQAovwuTb0SECQrcRiwlinVEVu9yZSjtT9hTCnTylViGQgjtWvGkMg65Ls+MQJMs+mc4T2M6C26KSkSzsy4FDiV6YyJhA4OZY+aOgAxWdpHAWVvd9ud6Zb3N9/OkwvrYeTxBjisjqtfZ4ALwXkI6AGUIPfNyBsHrWWxM7uQFhuDMGg/UWQ9XTWRJT2OGlywnaCcmrUg0wbYUQAAFRGVMPAzCYcT/MZ92JF0yRPTYrxg8dKwQBkqk+JlxTNR9RQY99pVleVcMVDplVVeB1U1bVdVNEjiBNA1wUXZirQILCOloBhmFAklwPJCQpBub1DD9Ywg20XQay0iM7lrakUNsZtSlkvdex3PECN7IiBwgocyLPCjLzcmivg0Vd5wkpiQBXOd1z4pDsJ7X87Jwg9lJElyqIvODqS80TxQAfW4MhoCoCR/MbEBLRTMK233WyOmRBY81i49INc6DEqoi4AA4rhBWQ7ky7LcuPL5oGwABrdQAG1QA4BYkFYTIOA0DpgGAXRoA0T4QEqABdL43GQuNUIw9ErPxCLOK7A720co9B2LNyGvIry6M+IAAA==&value=N4IgdghgtgpiBcIQBoQBMYGcDGAnAlgA4Au+A9mAkqpgBZm7EY4EnmWIoj5QQDmWAEwIA2gF1UPfllFiAvkAAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&no_additional_properties)

But, when I try it at Angular JSON Editor (latest version), the Images and Images2 are not displayed:
![screen shot 2015-11-23 at 9 08 06 pm](https://cloud.githubusercontent.com/assets/4828083/11352894/5614daac-9226-11e5-988d-111fa9e1e22e.png)

Any idea how to fix it?

**Comment by rodikh** [comment]
Hey,

Did you remember to add the empty arrays to startVal, like so:
```js
{
  "name": "",
  "description": "",
  "shortdescription": "",
  "images2": [],
  "images": []
}
```

Non-required properties with undefined startVal will not be displayed in the form by default. This is by design of the original json-editor plugin.

**Comment by elijahvsjesus** [comment]
Thanks very much, it works fine now.
