### ISSUE TITLE
Selectize.js Options Support

### ISSUE THREAD

**Issue by elijahvsjesus** [rodikh/angular-json-editor#23]
Hello,

I'm trying to use Selectize.js plugin supported by JSON Editor.
https://github.com/jdorn/json-editor#select2--selectize-support
http://brianreavis.github.io/selectize.js/

I can use the "enable: true" no problem with angular-json-editor, like this:
```
JSONEditorProvider.configure({
		selectize: {
			enable: true
		}
});
```

But, when I try to add Selectize options such as "create: false", it does not initialize it with them.

Any help?

**Comment by rodikh** [comment]
Setting plugin configurations is done like so:
```js
    JSONEditorProvider.configure({
        plugins: {
            selectize: {
                enable: true
            }
        }
    }
```
You are missing the plugins property.

alternatively, selectize options can be set in the schema, as in the following example:
https://github.com/jdorn/json-editor/blob/master/examples/selectize.html

**Comment by elijahvsjesus** [comment]
Hello,

Sorry, it was a typo. I'm working exactly as you posted.
But, create: false flag is not working. Have you tried it out?

Regards,

**Comment by elijahvsjesus** [comment]
Hello,

After some debugging, I've found that the "create" option is being overwritter in line 5265 from jsoneditor.js, no relation to "angular-json-editor. 

Moved the issue to jdorn/json-editor github:
https://github.com/jdorn/json-editor/issues/538

**Comment by rodikh** [comment]
Thanks for doing the research!
Let me know if I need to update my plugin after jdorn's issue is resolved.
