### ISSUE TITLE
Not able to use angular-json-editor and ng-jsoneditor together

### ISSUE THREAD

**Issue by amanguptadev** [rodikh/angular-json-editor#25]
Hey,

I'm stuck into a problem,
angular-json-editor and [ng-json-editor](https://github.com/angular-tools/ng-jsoneditor) both are using a json-editor.js file, so i'm facing some conflict problem and not able to solve issue by my self.

```
<json-editor schema="deviceSh" startval="deviceValSh" buttons-controller="addDeviceED1Ctrl" id='editor_holder'>
        </json-editor>
```

The directive above is loading ng-json-editor not angular-json-editor.

**Comment by rodikh** [comment]
Hey,

I am not familiar with ng-json-editor, so I am not sure as to what is it's purpose.

Other than that, I don't see any reason for a conflict, as angular-json-editor uses the Element restriction for the directive, and ng-json-editor (as far as I can see) uses the Attribute restriction.

This means that `<json-editor>` which calls my directive, is different from `<div json-editor>` which calls ng-json-editor's directive.

**Comment by rodikh** [comment]
Hey,

Can you explain more about your use case?
What is ng-json-editor, and what is it's use?

I am not sure how Angular handles multiple directives with the same name, so it might be overwriting my directive with ng-json-editor's definition.

**Comment by shatting** [comment]
had the same problem. the problem is that both json editors use window.JSONEditor. i ended up renaming one.

```
        <!-- this is https://github.com/josdejong/jsoneditor, and will be exposed as window.JSONTreeEditor -->
        <script src="bower_components/jsoneditor/dist/jsoneditor.min.js"></script>
        <script type="text/javascript">
            window.JSONTreeEditor = window.JSONEditor
            delete window.JSONEditor
        </script>
        <!-- this is a wrapper around the above, directive called <ng-json-tree-editor> -->
        <script src="/ng-json-tree-editor.js"></script>
        <!--this is https://github.com/jdorn/json-editor, and will be exposed as window.JSONEditor-->
        <script src="bower_components/json-editor/dist/jsoneditor.js"></script>
        <!--wrapper around the above (https://github.com/rodikh/angular-json-editor), directive called <json-editor> -->
        <script src="bower_components/angular-json-editor/dist/angular-json-editor.js"></script>
```
