### ISSUE TITLE
Error: buttons-controller attribute must be a valid controller

### ISSUE THREAD

**Issue by simo3o** [rodikh/angular-json-editor#29]
I'm getting this error just injecting $uibModalInstace from bootstrap modals, I have it loaded as I can inject it in the main controller of the json-editor, but not on the buttons-controller.

Any idea?
this is my buttons controller:

```
    .controller('AsyncButtonsController', function ($scope, $uibModalInstance) {
        $scope.onSubmit = function () {
            console.log('onSubmit data in async controller', $scope.editor.getValue());
        };

        $scope.onAction2 = function () {
            console.log('onAction2');
        };
        $scope.cancel = function () {
            $uibModalInstance.dismiss('cancel');

        }
    })
```
Thanks

**Comment by simo3o** [comment]
I've just fixed it it was set as  no_additional_properties: true,on the config.

**Comment by rodikh** [comment]
Sorry for not being responsive, I'm a bit swamped. I'm glad you solved the issue.

Is this an appropriate solution to your issue?
