### ISSUE TITLE
How to mark a field as required?

### ISSUE THREAD

**Issue by mariusheil** [rodikh/angular-json-editor#36]
Hi,

I am missing the possibility to access the current schema entry from the templating engine. When methods such as getFormInputField or getFormControl are called, I do not know how to access the part of the schema that is currently built.
I want to mark an HTML element with a required attribute so that it interfaces nicely with my page. Additionally this would enable us to use custom attributes in the schema to augment the view.

**Comment by rodikh** [comment]
Can you explain how you would do that with the original json-editor?
