### ISSUE TITLE
onChange Event not fired for boolean and null property value

### ISSUE THREAD

**Issue by elena89rossi** [rodikh/angular-json-editor#40]
Hi,
I've a  problem with json object with  boolean property.
If i write my json through "Properties" button all works fine.
If i write my json through "JSON" button the onChange event is not fired if my object have a boolean or null property.
The result is that the layout is updated while my data isn't updated.
( I've used version 0.2.1 but i try to reproduce the same case also using your demo page with the latest version of plugin )
![1](https://cloud.githubusercontent.com/assets/7147846/25857823/785feafe-34da-11e7-98c3-8c88c5052574.png)
![2](https://cloud.githubusercontent.com/assets/7147846/25858131/44565918-34db-11e7-8878-9fa34a3d2b53.png)

**Comment by rodikh** [comment]
Can you confirm that this works in the original jdorn/json-editor project?

**Comment by elena89rossi** [comment]
Sorry, the problem is in the original  jdorn/json-editor project.
