### ISSUE TITLE
Multiple grids in the same controller

### ISSUE THREAD

**Issue by scphantm** [rodikh/angular-json-editor#41]
I have a need to run about 4, maybe 5 completely different grids in the same controller, different configs, different schemas, different data.  To make matters worse, they can't all load at once.  Only when i execute the state machine function can they begin to load.  I am moving as much as i can to models to eliminate the uber controllers, but just the way this is put together, its not realistic to do it completely.

How would i pull this off?

**Comment by rodikh** [comment]
There is no problem putting several forms in the same page/controller.
You can look at the demo app to see an example of a page that has 3 differently configured forms.

It is also possible to dynamically add more forms to the page, as they are plain directives.

Do you need the different forms to communicate with each-other? That may require some scope juggling, but other than that it should be pretty straight-forward.
